import {
  Injectable,
  NestInterceptor,
  ExecutionContext,
  CallHandler,
} from "@nestjs/common";
import { Observable } from "rxjs";
import { tap } from "rxjs/operators";
import { Response } from "express";

@Injectable()
export class CacheControlInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const response = context.switchToHttp().getResponse<Response>();
    const request = context.switchToHttp().getRequest();

    return next.handle().pipe(
      tap(() => {
        const path = request.route?.path;

        // Set appropriate Cache-Control headers based on endpoint
        if (path?.includes("/health")) {
          // Health checks: cache for 30 seconds
          response.setHeader("Cache-Control", "public, max-age=30");
        } else if (path?.includes("/analytics")) {
          // Analytics: cache for 5 minutes
          response.setHeader("Cache-Control", "private, max-age=300");
        } else if (path?.includes("/metrics")) {
          // Metrics: cache for 1 minute
          response.setHeader("Cache-Control", "private, max-age=60");
        } else if (path?.includes("/analyze")) {
          // Analysis results: cache for 1 hour (private to user)
          response.setHeader("Cache-Control", "private, max-age=3600");
        } else {
          // Default: no cache for other endpoints
          response.setHeader(
            "Cache-Control",
            "no-cache, no-store, must-revalidate",
          );
        }

        // Add ETag support (auto-generated by Express)
        // ETags are automatically generated by Express for response bodies
      }),
    );
  }
}
